package vistas;

import dao.ArticuloDAO;
import models.Articulo;
import config.ConexionBD;
import models.ProveedorItem;

// Librerías para SQL y listas
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

// Librerías Swing y AWT
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmArticulos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmArticulos.class.getName());

    /**
     * Creates new form FrmArticulos
     */
    public FrmArticulos() {
        initComponents();
             
        cargarProveedores();
        listarArticulos();
        setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        cbxProveedor = new javax.swing.JComboBox<>();
        btnAtras = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("GESTIÓN DE ARTÍCULOS");

        lblCodigo.setText("Código:");

        lblProveedor.setText("Proveedor:");

        lblNombre.setText("Nombre:");

        lblDescripcion.setText("Descripción:");

        lblCantidad.setText("Cantidad:");

        lblPrecio.setText("Precio Unitario:");

        cbxProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProveedorItemStateChanged(evt);
            }
        });

        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "PROVEEDOR", "NOMBRE", "DESCRIPCION", "CANTIDAD", "PRECIO UNITARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArticulos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblArticulos);
        tblArticulos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblArticulos.getColumnModel().getColumnCount() > 0) {
            tblArticulos.getColumnModel().getColumn(0).setResizable(false);
            tblArticulos.getColumnModel().getColumn(1).setResizable(false);
            tblArticulos.getColumnModel().getColumn(2).setResizable(false);
            tblArticulos.getColumnModel().getColumn(3).setResizable(false);
            tblArticulos.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo)
                                    .addComponent(cbxProveedor, 0, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtras))
                            .addComponent(txtNombre)
                            .addComponent(txtDescripcion)
                            .addComponent(txtCantidad)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProveedor)
                    .addComponent(cbxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnReportes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        ArticuloDAO dao = new ArticuloDAO();
        Articulo articulo = new Articulo();

        //Validar campos vacíos
        if (txtCodigo.getText().trim().isEmpty() ||
            cbxProveedor.getSelectedIndex() == -1 ||
            txtNombre.getText().trim().isEmpty() ||
            txtDescripcion.getText().trim().isEmpty() ||
            txtCantidad.getText().trim().isEmpty() ||
            txtPrecio.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.", 
                                          "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Validar tipo de dato numerico
        int cantidad;
        double precio;
        try {
            cantidad = Integer.parseInt(txtCantidad.getText().trim());
            precio = Double.parseDouble(txtPrecio.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad y precio deben ser valores numéricos.", 
                                          "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Obtener el proveedor seleccionado
        ProveedorItem proveedorSeleccionado = (ProveedorItem) cbxProveedor.getSelectedItem();
        int idProveedor = proveedorSeleccionado.getIdProveedor();

        //Validar que el proveedor exista en BD
        if (!dao.existeProveedor(idProveedor)) {
            JOptionPane.showMessageDialog(this, "El proveedor seleccionado no existe.", 
                                          "Proveedor inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Validar ducplicidad por codigo o nombre
        if (dao.buscarArticuloPorCodigo(txtCodigo.getText().trim()) != null) {
            JOptionPane.showMessageDialog(this, "Ya existe un artículo con ese código.", 
                                          "Duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (dao.buscarPorNombre(txtNombre.getText().trim()) != null) {
            JOptionPane.showMessageDialog(this, "Ya existe un artículo con ese nombre.", 
                                          "Duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Asignar Valores al modelo
        articulo.setCodigo(txtCodigo.getText().trim());
        articulo.setIdProveedor(idProveedor);
        articulo.setNombre(txtNombre.getText().trim());
        articulo.setDescripcion(txtDescripcion.getText().trim());
        articulo.setCantidad(cantidad);
        articulo.setPrecio(precio);

        //Guardar el Articulo usando DAO
        if (dao.agregarArticulo(articulo)) {
            JOptionPane.showMessageDialog(this, "Artículo registrado correctamente.", 
                                          "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            listarArticulos(); // Refrescar la tabla
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el artículo.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
       
    }                                          

    private void cbxProveedorItemStateChanged(java.awt.event.ItemEvent evt) {                                              
        // TODO add your handling code here:

    }                                             

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        ArticuloDAO dao = new ArticuloDAO();
        Articulo articulo = null;

        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();

        // Validar que al menos un campo tenga valor
        if (codigo.isEmpty() && nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código o el nombre del articulo para buscar.", 
                                          "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Buscar por código o nombre
        if (!codigo.isEmpty()) {
            articulo = dao.buscarArticuloPorCodigo(codigo);
        } 
        if (articulo == null && !nombre.isEmpty()) {
            articulo = dao.buscarPorNombre(nombre);
        }

        // Validar si se encontró el artículo
        if (articulo != null) {
            txtCodigo.setText(articulo.getCodigo());
            txtNombre.setText(articulo.getNombre());
            txtDescripcion.setText(articulo.getDescripcion());
            txtCantidad.setText(String.valueOf(articulo.getCantidad()));
            txtPrecio.setText(String.valueOf(articulo.getPrecio()));

            // Seleccionar el proveedor en el ComboBox
            for (int i = 0; i < cbxProveedor.getItemCount(); i++) {
                ProveedorItem p = cbxProveedor.getItemAt(i);
                if (p.getIdProveedor() == articulo.getIdProveedor()) {
                    cbxProveedor.setSelectedIndex(i);
                    break;
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el articulo.", 
                                          "No encontrado", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        }
    }                                         

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        limpiarCampos();
    }                                          

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        // Abrir el formulario principal
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);

        // Cerrar el formulario actual
        this.dispose();
    }                                        

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
            ArticuloDAO dao = new ArticuloDAO();
            Articulo articulo = new Articulo();

            if (txtCodigo.getText().trim().isEmpty() ||
                txtNombre.getText().trim().isEmpty() ||
                txtDescripcion.getText().trim().isEmpty() ||
                txtCantidad.getText().trim().isEmpty() ||
                txtPrecio.getText().trim().isEmpty() ||
                cbxProveedor.getSelectedIndex() == -1) {

                JOptionPane.showMessageDialog(this, "Complete todos los campos antes de modificar.", 
                                              "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            articulo.setCodigo(txtCodigo.getText().trim());
            articulo.setNombre(txtNombre.getText().trim());
            articulo.setDescripcion(txtDescripcion.getText().trim());

            try {
                articulo.setCantidad(Integer.parseInt(txtCantidad.getText().trim()));
                articulo.setPrecio(Double.parseDouble(txtPrecio.getText().trim()));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cantidad y precio deben ser valores numéricos.", 
                                              "Error de formato", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ProveedorItem proveedorSeleccionado = (ProveedorItem) cbxProveedor.getSelectedItem();
            articulo.setIdProveedor(proveedorSeleccionado.getIdProveedor());

            if (dao.actualizarArticulo(articulo)) {
                JOptionPane.showMessageDialog(this, "Artículo modificado correctamente.",
                                              "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                listarArticulos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar el artículo.",
                                              "Error", JOptionPane.ERROR_MESSAGE);
            }
    }                                            

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        ArticuloDAO dao = new ArticuloDAO();

        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();

        // Validar que al menos haya un identificador
        if (codigo.isEmpty() && nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el codigo o nombre del articulo para eliminar.", 
                                          "Campo vacio", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirmar eliminación
        int opcion = JOptionPane.showConfirmDialog(this, 
                        "¿Esta seguro que desea eliminar este artículo?", 
                        "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (opcion != JOptionPane.YES_OPTION) {
            return; // Si el usuario cancela, no hacemos nada
        }

        boolean eliminado = false;

        // Intentar eliminar por código si está disponible
        if (!codigo.isEmpty()) {
            eliminado = dao.eliminarPorCodigo(codigo);
        }

        // Si no se eliminó por código, intentar por nombre
        if (!eliminado && !nombre.isEmpty()) {
            eliminado = dao.eliminarPorNombre(nombre);
        }

        // Mensajes según el resultado
        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Articulo eliminado correctamente.", 
                                          "Exito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            listarArticulos(); // Refresca la tabla
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el artículo o no existe.", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                           

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        FrmReportes reporte = new FrmReportes();
        reporte.setVisible(true);

        // Cerrar el formulario actual
        this.dispose();
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmArticulos().setVisible(true));
    }

    private void limpiarCampos() {
        txtCodigo.setText("");
        cbxProveedor.setSelectedIndex(-1);
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
    }

    private void listarArticulos() {
        ArticuloDAO dao = new ArticuloDAO();
        List<Articulo> lista = dao.listarArticulos();

        // Definir las columnas de la tabla
        String[] columnas = {"ID", "Codigo", "Proveedor", "Nombre", "Descripcion", "Cantidad", "Precio"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);

        // Llenar la tabla
        for (Articulo a : lista) {
            Object[] fila = new Object[7];
            fila[0] = a.getIdArticulo();
            fila[1] = a.getCodigo();
            fila[2] = a.getIdProveedor();
            fila[3] = a.getNombre();
            fila[4] = a.getDescripcion();
            fila[5] = a.getCantidad();
            fila[6] = a.getPrecio();
            modelo.addRow(fila);
        }

        tblArticulos.setModel(modelo);
    }
  
    
    
    
    private void cargarProveedores() {
        cbxProveedor.removeAllItems();
        String sql = "SELECT id_proveedor, nombre FROM proveedores";

        try (Connection con = ConexionBD.getConexion();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                cbxProveedor.addItem(new ProveedorItem(rs.getInt("id_proveedor"), rs.getString("nombre")));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar proveedores: " + e.getMessage());
        }
    }

    
        
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<ProveedorItem> cbxProveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblArticulos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration                   
}
