package vistas;

import dao.ArticuloDAO;
import dao.ClienteDAO;
import dao.EmpleadoDAO;
import dao.FacturaDAO;
import dao.DetalleFacturaDAO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import models.Articulo;
import models.Cliente;
import models.Empleado;
import models.Factura;
import models.DetalleFactura;
import models.GenerarFacturaHTML;
import java.util.ArrayList;
import java.util.List;

public class FrmFacturacion extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private final ArticuloDAO articuloDAO;
    private final int idClienteSeleccionado = -1;
    private final Empleado empleadoSeleccionado = null;
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmFacturacion.class.getName());

    /**
     * Creates new form FrmFacturacion
     */
    public FrmFacturacion() {
        initComponents();
        setLocationRelativeTo(null);
        
        articuloDAO = new ArticuloDAO(); // Crear instancia DAO para consultas
        modelo = (DefaultTableModel) tblArticulos.getModel();
        
        cargarEmpleados(); // Llenar el JComboBox de facturacion al iniciar
                
        // Listener para actualizar nombre, precio y subtotal automáticamente
        modelo.addTableModelListener(e -> {
            int fila = e.getFirstRow();
            int columna = e.getColumn();

            if (columna == 0) { // Código modificado
                String codigo = String.valueOf(modelo.getValueAt(fila, 0));
                Articulo articulo = buscarArticuloPorCodigo(codigo);
                if (articulo != null) {
                    modelo.setValueAt(articulo.getNombre(), fila, 1);
                    modelo.setValueAt(articulo.getPrecio(), fila, 2);
                    modelo.setValueAt(1, fila, 3);
                    modelo.setValueAt(articulo.getPrecio(), fila, 4);
                } else {
                    JOptionPane.showMessageDialog(this, "Artículo no encontrado");
                    modelo.setValueAt("", fila, 1);
                    modelo.setValueAt("", fila, 2);
                    modelo.setValueAt("", fila, 3);
                    modelo.setValueAt("", fila, 4);
                }
            }

            if (columna == 3) {
                try {
                    int cantidad = Integer.parseInt(String.valueOf(modelo.getValueAt(fila, 3)));
                    double precio = Double.parseDouble(String.valueOf(modelo.getValueAt(fila, 2)));
                    modelo.setValueAt(cantidad * precio, fila, 4);
                } catch (Exception ex) {
                    modelo.setValueAt(0, fila, 4);
                }
            }
            actualizarTotal();
        });
        
    }
    
    public class EmpleadoComboItem {
            private Empleado empleado;
            public EmpleadoComboItem(Empleado empleado) {
                this.empleado = empleado;
                }
            public Empleado getEmpleado() {
                return empleado;
                }
             @Override
             public String toString() {
                 return empleado.getNombre(); //solo muestra el nombre en el combo
                 }
             }
    
        private void actualizarTotal() {
            double total = 0;
            for (int i = 0; i < modelo.getRowCount(); i++) {
                Object valor = modelo.getValueAt(i, 4);
                if (valor != null) {
                    try {
                        total += Double.parseDouble(valor.toString());
                    } catch (NumberFormatException e) {
                        // ignorar filas inválidas
                    }
                }
            }
            txtTotal.setText(String.format("%.2f", total));
        }
        
    
     private void cargarEmpleados() {
         EmpleadoDAO empleadoDAO = new EmpleadoDAO();
         List<Empleado> empleados = empleadoDAO.obtenerTodos();
         cbxEmpleado.removeAllItems(); // Limpiar elementos previos
         
         for (Empleado e : empleados) {
              cbxEmpleado.addItem(new EmpleadoComboItem(e));
        }
    }
     
        private Articulo buscarArticuloPorCodigo(String codigo) {
        return articuloDAO.obtenerArticuloParaFactura(codigo);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNIT = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblDireccionCliente = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        lblEmpleado = new javax.swing.JLabel();
        cbxEmpleado = new javax.swing.JComboBox<>();
        lblNumeroCaja = new javax.swing.JLabel();
        txtNumeroCaja = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();
        btnAgregarArticulo = new javax.swing.JButton();
        btnQuitarArticulo = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnGenerarFactura = new javax.swing.JButton();
        btnCancelarFactura = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnModificarFactura = new javax.swing.JButton();
        btnBuscarFactura = new javax.swing.JButton();
        btnEliminarFactura = new javax.swing.JButton();
        btnReporteFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FACTURACION");

        lblNIT.setText("NIT:");

        btnBuscarCliente.setText("BUSCAR");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblNombreCliente.setText("Nombre:");

        lblDireccionCliente.setText("Direccion:");

        lblEmpleado.setText("Empleado:");

        cbxEmpleado.setName(""); // NOI18N
        cbxEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEmpleadoActionPerformed(evt);
            }
        });

        lblNumeroCaja.setText("No. Caja:");

        tblArticulos.setModel( new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"Código", "Nombre", "Precio", "Cantidad", "Subtotal"}
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        }
    );
    tblArticulos.setColumnSelectionAllowed(true);
    jScrollPane1.setViewportView(tblArticulos);
    tblArticulos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    btnAgregarArticulo.setText("+ Articulo");
    btnAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAgregarArticuloActionPerformed(evt);
        }
    });

    btnQuitarArticulo.setText("- Articulo");
    btnQuitarArticulo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnQuitarArticuloActionPerformed(evt);
        }
    });

    lblTotal.setText("TOTAL:");

    btnGenerarFactura.setText("GENERAR FACTURA");
    btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGenerarFacturaActionPerformed(evt);
        }
    });

    btnCancelarFactura.setText("CANCELAR FACTURA");

    btnAtras.setText("ATRAS");
    btnAtras.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAtrasActionPerformed(evt);
        }
    });

    btnModificarFactura.setText("MODIFICAR FACTURA");

    btnBuscarFactura.setText("BUSCAR FACTURA");
    btnBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBuscarFacturaActionPerformed(evt);
        }
    });

    btnEliminarFactura.setText("ELIMINAR FACTURA");
    btnEliminarFactura.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEliminarFacturaActionPerformed(evt);
        }
    });

    btnReporteFactura.setText("REPORTE DE FACTURAS");
    btnReporteFactura.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnReporteFacturaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btnGenerarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReporteFactura))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btnCancelarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblNumeroCaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(lblDireccionCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNIT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNIT)
                                .addComponent(txtNombreCliente)
                                .addComponent(txtDireccionCliente)
                                .addComponent(cbxEmpleado, 0, 182, Short.MAX_VALUE)
                                .addComponent(txtNumeroCaja))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnQuitarArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 6, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNIT)
                .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBuscarCliente))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNombreCliente)
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAtras))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDireccionCliente)
                .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnQuitarArticulo))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblEmpleado)
                .addComponent(cbxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAgregarArticulo))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblNumeroCaja)
                .addComponent(txtNumeroCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblTotal))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnCancelarFactura)
                .addComponent(btnGenerarFactura))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnModificarFactura)
                .addComponent(btnBuscarFactura))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnEliminarFactura)
                .addComponent(btnReporteFactura))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>                        

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);

        // Cerrar el formulario actual
        this.dispose();
    }                                        

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        String searchQuery = txtNIT.getText().trim();
        ClienteDAO clienteDAO = new ClienteDAO();
        Cliente cliente = clienteDAO.buscarPorNit(searchQuery);

        if (cliente == null) {
            cliente = clienteDAO.buscarPorNombre(searchQuery);
        }

        if (cliente != null) {
            txtNombreCliente.setText(cliente.getNombre());
            txtDireccionCliente.setText(cliente.getDireccion());
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado. ¿Desea agregarlo?",
                    "Cliente no encontrado", JOptionPane.INFORMATION_MESSAGE);
        }
    }                                                

    private void btnAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
         modelo.addRow(new Object[]{"", "", 0.0, 1, 0.0});
        
    }                                                  

    private void btnReporteFacturaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        new FrmReportes().setVisible(true);
        this.dispose(); //Cerramos el actual
    }                                                 

    private void btnQuitarArticuloActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        int fila = tblArticulos.getSelectedRow();
        if (fila >= 0) {
            modelo.removeRow(fila);
            actualizarTotal();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar");
        }
    }                                                 

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        // Validaciones iniciales
        if (txtNombreCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente antes de generar la factura");
            return;
        }
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Agregue al menos un artículo a la factura");
            return;
        }

        // Obtener empleado seleccionado
        EmpleadoComboItem item = (EmpleadoComboItem) cbxEmpleado.getSelectedItem();
        if (item == null || item.getEmpleado() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado");
            return;
        }
        Empleado empleado = item.getEmpleado();

        // Obtener cliente por NIT
        ClienteDAO clienteDAO = new ClienteDAO();
        Cliente cliente = clienteDAO.buscarPorNit(txtNIT.getText().trim());
        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado");
            return;
        }

        // Crear factura
        Factura factura = new Factura();
        factura.setIdCliente(cliente.getIdCliente());
        factura.setIdEmpleado(empleado.getIdEmpleado());
        factura.setNumeroCaja(Integer.parseInt(txtNumeroCaja.getText()));
        factura.setNumeroFactura(new FacturaDAO().generarNumeroFactura());
        factura.setFecha(new java.util.Date());
        factura.setTotal(Double.parseDouble(txtTotal.getText()));

        // Crear detalles de la factura
        List<DetalleFactura> detalles = new ArrayList<>();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String codigo = String.valueOf(modelo.getValueAt(i, 0));
            if (codigo == null || codigo.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Artículo inválido en la fila " + (i + 1));
                return;
            }

            Articulo articulo = articuloDAO.obtenerArticuloParaFactura(codigo);
            if (articulo == null) {
                JOptionPane.showMessageDialog(this, "Artículo no encontrado en la fila " + (i + 1));
                return;
            }

            DetalleFactura detalle = new DetalleFactura();
            detalle.setIdArticulo(articulo.getIdArticulo());        // FK correcta
            detalle.setNombreArticulo(articulo.getNombre());       // Nombre para HTML
            detalle.setCantidad(Integer.parseInt(modelo.getValueAt(i, 3).toString()));
            detalle.setPrecioUnitario(articulo.getPrecio());
            //detalle.setSubtotal(detalle.getCantidad() * detalle.getPrecioUnitario());

            detalles.add(detalle);
        }
        factura.setDetalles(detalles);

        // Guardar factura y detalles en BD
        FacturaDAO facturaDAO = new FacturaDAO();
        if (facturaDAO.guardarFactura(factura)) {
            DetalleFacturaDAO detalleDAO = new DetalleFacturaDAO();
            for (DetalleFactura d : detalles) {
                d.setIdFactura(factura.getIdFactura());
                if (!detalleDAO.guardarDetalle(d)) {
                    JOptionPane.showMessageDialog(this, "Error al guardar detalle de artículo: " + d.getNombreArticulo());
                }
            }

            // Generar factura HTML
            GenerarFacturaHTML.generar(factura, detalles, txtNombreCliente.getText(), empleado.getNombre());

            // Limpiar tabla y campos
            modelo.setRowCount(0);
            txtTotal.setText("0.00");
            txtNombreCliente.setText("");
            txtDireccionCliente.setText("");
            txtNIT.setText("");
            txtNumeroCaja.setText("");

            JOptionPane.showMessageDialog(this, "Factura generada correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar la factura");
        }
    }                                                 

    private void cbxEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Ingrese el número de factura a buscar:");
        if (input == null || input.trim().isEmpty()) {
            return; // Cancelado o vacío
        }

        try {
            int numeroFactura = Integer.parseInt(input.trim());
            FacturaDAO facturaDAO = new FacturaDAO();
            Factura factura = facturaDAO.buscarFactura(numeroFactura);

            if (factura != null) {
                // Cargar datos del cliente
                ClienteDAO clienteDAO = new ClienteDAO();
                Cliente cliente = clienteDAO.obtenerPorId(factura.getIdCliente());
                if (cliente != null) {
                    txtNIT.setText(cliente.getNit());
                    txtNombreCliente.setText(cliente.getNombre());
                    txtDireccionCliente.setText(cliente.getDireccion());
                } else {
                    txtNIT.setText("");
                    txtNombreCliente.setText("");
                    txtDireccionCliente.setText("");
                }

                // Cargar datos del empleado
                EmpleadoDAO empleadoDAO = new EmpleadoDAO();
                Empleado empleado = empleadoDAO.obtenerPorId(factura.getIdEmpleado());
                if (empleado != null) {
                    cbxEmpleado.setSelectedItem(new EmpleadoComboItem(empleado));
                }

                // Mostrar otros datos
                txtNumeroCaja.setText(String.valueOf(factura.getNumeroCaja()));
                txtTotal.setText(String.format("%.2f", factura.getTotal()));

                // Cargar detalles en la tabla
                DefaultTableModel modelo = (DefaultTableModel) tblArticulos.getModel();
                modelo.setRowCount(0);
                for (DetalleFactura d : factura.getDetalles()) {
                    Object[] fila = {
                        d.getIdArticulo(),
                        d.getNombreArticulo(),
                        d.getPrecioUnitario(),
                        d.getCantidad(),
                        d.getSubtotal()
                    };
                    modelo.addRow(fila);
                }

                JOptionPane.showMessageDialog(this, "Factura cargada correctamente.");

            } else {
                JOptionPane.showMessageDialog(this, "Factura no encontrada.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de factura válido.");
        }
    }                                                

    private void btnEliminarFacturaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Ingrese el número de factura que desea eliminar:");
        if (input == null || input.trim().isEmpty()) {
            return; // Cancelado o vacío
        }

        try {
            int numeroFactura = Integer.parseInt(input.trim());
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de eliminar la factura N° " + numeroFactura + "?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                FacturaDAO facturaDAO = new FacturaDAO();
                boolean eliminado = facturaDAO.eliminarFacturaPorNumero(numeroFactura);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Factura eliminada correctamente.");
                    // Limpiar los campos y tabla
                    txtNIT.setText("");
                    txtNombreCliente.setText("");
                    txtDireccionCliente.setText("");
                    txtNumeroCaja.setText("");
                    txtTotal.setText("0.00");
                    ((DefaultTableModel) tblArticulos.getModel()).setRowCount(0);
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró la factura o ocurrió un error al eliminarla.");
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de factura válido.");
        }
    }                                                  

    private Articulo buscarArticuloPorCodigo(Object valueAt) {
        return articuloDAO.obtenerArticuloParaFactura(String.valueOf(valueAt));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmFacturacion().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAgregarArticulo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarFactura;
    private javax.swing.JButton btnCancelarFactura;
    private javax.swing.JButton btnEliminarFactura;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnModificarFactura;
    private javax.swing.JButton btnQuitarArticulo;
    private javax.swing.JButton btnReporteFactura;
    private javax.swing.JComboBox<Object> cbxEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccionCliente;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblNIT;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumeroCaja;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblArticulos;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumeroCaja;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration                   
}
