package vistas;

import java.io.*;
import java.sql.*;
import java.awt.Desktop;

import config.ConexionBD;
import dao.DetalleFacturaDAO;
import dao.FacturaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.DetalleFactura;
import models.Factura;

public class FrmReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    FrmReportes(FrmPrincipal aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnReporteArticulos = new javax.swing.JButton();
        btnReporteProveedores = new javax.swing.JButton();
        btnReporteClientes = new javax.swing.JButton();
        btnReporteEmpleados = new javax.swing.JButton();
        btnReporteFacturas = new javax.swing.JButton();
        lblReferencia = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblDesarrollador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("GESTIÓN DE REPORTES");

        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnReporteArticulos.setText("REPORTE DE ARTICULOS");
        btnReporteArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteArticulosActionPerformed(evt);
            }
        });

        btnReporteProveedores.setText("REPORTE DE PROVEEDORES");
        btnReporteProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteProveedoresActionPerformed(evt);
            }
        });

        btnReporteClientes.setText("REPORTE DE CLIENTES");
        btnReporteClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteClientesActionPerformed(evt);
            }
        });

        btnReporteEmpleados.setText("REPORTE DE EMPLEADOS");
        btnReporteEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEmpleadosActionPerformed(evt);
            }
        });

        btnReporteFacturas.setText("REPORTE DE FACTURAS");
        btnReporteFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteFacturasActionPerformed(evt);
            }
        });

        lblReferencia.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblReferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReferencia.setText("Diseñado y Desarrollado por");

        lblEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpresa.setText("GENERANDO BITS");

        lblDesarrollador.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblDesarrollador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesarrollador.setText("Jairon Taque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnReporteArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReporteProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(btnReporteClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReporteEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReporteFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDesarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnAtras)
                .addGap(18, 18, 18)
                .addComponent(btnReporteArticulos)
                .addGap(18, 18, 18)
                .addComponent(btnReporteProveedores)
                .addGap(18, 18, 18)
                .addComponent(btnReporteClientes)
                .addGap(18, 18, 18)
                .addComponent(btnReporteEmpleados)
                .addGap(18, 18, 18)
                .addComponent(btnReporteFacturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblReferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesarrollador)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void btnReporteArticulosActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        String sql = "SELECT codigo, nombre, descripcion, cantidad, precio FROM articulos";
        String[] columnas = {"codigo", "nombre", "descripcion", "cantidad", "precio"};

        try (Connection con = ConexionBD.getConexion();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            generarReporteHTML(rs, "Reporte_Articulos.html", "Reporte de Articulos", columnas);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte de articulos: " + e.getMessage());
        }
    }                                                   

    private void btnReporteProveedoresActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
         String sql = "SELECT nit, nombre, direccion, telefono FROM proveedores";
        String[] columnas = {"nit", "nombre", "direccion", "telefono"};

        try (Connection con = ConexionBD.getConexion();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            generarReporteHTML(rs, "Reporte_Proveedores.html", "Reporte de Proveedores", columnas);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte de proveedores: " + e.getMessage());
        }
    }                                                     

    private void btnReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
         String sql = "SELECT nit, nombre, direccion FROM clientes";
        String[] columnas = {"nit", "nombre", "direccion"};

        try (Connection con = ConexionBD.getConexion();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            generarReporteHTML(rs, "Reporte_Clientes.html", "Reporte de Clientes", columnas);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte de clientes: " + e.getMessage());
        }
    }                                                  

    private void btnReporteEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
         String sql = "SELECT codigo, nombre, puesto, salario FROM empleados";
        String[] columnas = {"codigo", "nombre", "puesto", "salario"};

        try (Connection con = ConexionBD.getConexion();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            generarReporteHTML(rs, "Reporte_Empleados.html", "Reporte de Empleados", columnas);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte de empleados: " + e.getMessage());
        }
    }                                                   

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);

        this.dispose();
    }                                        

    private void btnReporteFacturasActionPerformed(java.awt.event.ActionEvent evt) {                                                   
         // TODO add your handling code here:
            String sql = "SELECT f.numero_factura, f.id_cliente, f.id_empleado, f.fecha, f.total, f.numero_caja, " +
                    "a.nombre AS articulo, d.cantidad, d.precio_unitario, d.subtotal " +
                    "FROM facturas f " +
                    "INNER JOIN detalle_factura d ON f.id_factura = d.id_factura " +
                    "INNER JOIN articulos a ON d.id_articulo = a.id_articulo " +
                    "ORDER BY f.numero_factura";

       // Columnas que se mostrarán en el HTML
       String[] columnas = {"numero_factura", "id_cliente", "id_empleado", "fecha", "total", "numero_caja",
                            "articulo", "cantidad", "precio_unitario", "subtotal"};

       try (Connection con = ConexionBD.getConexion();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()) {

           // Llamamos al método funcional que ya genera HTML
           generarReporteHTML(rs, "Reporte_Facturas.html", "Reporte de Facturas", columnas);

           JOptionPane.showMessageDialog(this, "Reporte de facturas generado correctamente.");

       } catch (SQLException e) {
           JOptionPane.showMessageDialog(this, "Error al generar reporte de facturas: " + e.getMessage());
           e.printStackTrace();
       }       
    }                                                  

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

        public void generarReporteHTML(ResultSet rs, String nombreArchivo, String titulo, String[] columnas) {
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo));

                writer.write("<html><head><title>" + titulo + "</title></head><body>");
                writer.write("<h2>" + titulo + "</h2>");
                writer.write("<table border='1' style='border-collapse:collapse;'>");

                // Encabezados
                writer.write("<tr>");
                for (String col : columnas) {
                    writer.write("<th>" + col + "</th>");
                }
                writer.write("</tr>");

                // Filas
                while (rs.next()) {
                    writer.write("<tr>");
                    for (String col : columnas) {
                        writer.write("<td>" + rs.getString(col) + "</td>");
                    }
                    writer.write("</tr>");
                }

                writer.write("</table></body></html>");
                writer.close();

                // Abrir automáticamente en el navegador
                Desktop.getDesktop().browse(new File(nombreArchivo).toURI());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al generar reporte: " + e.getMessage());
                e.printStackTrace();
            }
    }
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnReporteArticulos;
    private javax.swing.JButton btnReporteClientes;
    private javax.swing.JButton btnReporteEmpleados;
    private javax.swing.JButton btnReporteFacturas;
    private javax.swing.JButton btnReporteProveedores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDesarrollador;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration                   
}
